### ISSUE TITLE
Crash when moving console window in versions > 2.0.15

### ISSUE THREAD

**Issue by robrik** [poxet/tharga-console#7] opened 2017-08-25 18:51 UTC
I don't know if this is the right place but :) 
I'm using VS2017 and packet from NuGet. When doing the basic example in a C# console application template (see below) if i move the console window i get a crash.

Its only a debug exception (as it says, if I run the .exe it works) but its kinda annoying because I run in debug mode a lot.

This is what I get: Managed Debugging Assistant 'CallbackOnCollectedDelegate' 
The rest of the debug text is in Swedish for some reason so I can really paste it here. Maybe this is just me doing something wrong if so please let me know and remove this issue.

---------------------------------------------
namespace ConsoleApp1
{
using System;
using Tharga.Toolkit.Console;
using Tharga.Toolkit.Console.Commands;
using Tharga.Toolkit.Console.Consoles;
    internal static class Program
    {
        [STAThread]
        private static void Main(string[] args)
        {
            using (var console = new ClientConsole())
            {
                var command = new RootCommand(console);
                var engine = new CommandEngine(command);
                engine.Start(args);
            }
        }
    }
}
-------------------------------------------------

Best regards
Robert

**Comment by poxet** [comment] 2017-08-25 19:07
Try this temporary workaround...

new ClientConsole(new ConsoleConfiguration { RememberStartPosition = false })

I will have a closer look to see what the cause of the problem could be.

**Comment by poxet** [comment] 2017-08-25 19:19
@robrik what version of windows are you running?

**Comment by robrik** [comment] 2017-08-26 07:24
Windows 10 Home 64-bit (10.0, build15063)

**Comment by poxet** [comment] 2017-10-29 19:51
Fixed in version 2.0.48

**Closed by poxet** 2017-10-29 19:51 UTC
Labels: bug, help wanted
